name: AWS Lambda CI/CD-test
on:
  push:
    branches: ["backend-dev"]
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build UploadPost Lambda function and push to ecr
        id: build-image-upload-post
        working-directory: code/backend/RentalNinja/UploadPost
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: rentalninja/upload_post
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mvn compile dependency:copy-dependencies -DincludeScope=runtime
          mvn test
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo "IMAGE=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
